test 29

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -26,33 +26,33 @@ jobs:
       - name: gradlew permission
         run: chmod +x gradlew
 
-  build:
-    needs: setup_gradle
-
-    runs-on: ubuntu-latest
-
-    steps:
-      - uses: actions/checkout@v4
-      - name: Setup Java
-        uses: actions/setup-java@v4
-        with:
-          distribution: 'temurin'
-          java-version: 21
-          cache: gradle
-
-      - name: Setup Gradle
-        uses: gradle/actions/setup-gradle@v3
-
-      - uses: gradle/gradle-build-action@v3
-        with:
-          cache-read-only: false
-          gradle-version: wrapper
-          cache-disabled: false
-          cache-write-only: false
-          gradle-home-cache-includes: caches
-
-      - name: Gradle Build
-        run: ./gradlew build
+#  build:
+#    needs: setup_gradle
+#
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#      - uses: actions/checkout@v4
+#      - name: Setup Java
+#        uses: actions/setup-java@v4
+#        with:
+#          distribution: 'temurin'
+#          java-version: 21
+#          cache: gradle
+#
+#      - name: Setup Gradle
+#        uses: gradle/actions/setup-gradle@v3
+#
+#      - uses: gradle/gradle-build-action@v3
+#        with:
+#          cache-read-only: false
+#          gradle-version: wrapper
+#          cache-disabled: false
+#          cache-write-only: false
+#          gradle-home-cache-includes: caches
+#
+#      - name: Gradle Build
+#        run: ./gradlew build
 
 
   detekt:
@@ -75,13 +75,17 @@ jobs:
 
       - name: Run Detekt
         run: ./gradlew detekt
-
-      - name: Check Detekt Report Directory
-        run: ls
-
-      - name: Upload Detekt Reports
         uses: github/codeql-action/upload-sarif@v3
         if: success() || failure()
         with:
           sarif_file: detekt.sarif
+
+      - name: Check Detekt Report Directory
+        run: ls
+
+#      - name: Upload Detekt Reports
+#        uses: github/codeql-action/upload-sarif@v3
+#        if: success() || failure()
+#        with:
+#          sarif_file: detekt.sarif
 
